version: '3'
services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: FitTrackerApp
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33006:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
