version: '3'
services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: FitTrackerApp
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33006:3306"
    volumes:
      - /c/Users/mjktb/OneDrive/Dokumenty/projects/FitTrackerApp/volumes/db:/var/lib/mysql

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "9090:8080"
    volumes:
      - /c/Users/mjktb/OneDrive/Dokumenty/projects/FitTrackerApp/volumes/jenkins

volumes:
  mysql_data:
