version: '3'
services:

  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: FitTrackerApp
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33006:3306"
    volumes:
      - /c/Users/mjktb/OneDrive/Dokumenty/projects/FitTrackerApp/volumes/db:/var/lib/mysql

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "9091:8080"
    volumes:
      - /c/Users/mjktb/OneDrive/Dokumenty/projects/FitTrackerApp/volumes/jenkins

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8082:80"


volumes:
  mysql_data:
  jenkins_data: