spring:
  datasource:
    url: ${DB_URL}  #jdbc:mysql://localhost:3306/FitTrackerApp
    username: ${DB_USERNAME} #root
    password: ${DB_PASSWORD} #root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
        hibernate:
            format_sql: true
    defer-datasource-initialization: false
  flyway:
    enabled: false
    baseline-on-migrate: true
    user: root
    password: root
    baseline-description: "Baseline for FitTrackerApp"
    locations: classpath:db/migration
logging:
  level:
    org.springframework: DEBUG
    app: DEBUG

server:
  port: 8081




api:
  products:
    url: ${PRODUCTS_API_URL} #"https://api.edamam.com/api/food-database/v2/parser"
    key: ${PRODUCTS_API_KEY} #"919ca3a0f24fe88e3f071676227e522b"
    id: ${PRODUCTS_API_ID} #"74461f79"

  recipes:
    url: ${RECIPES_API_URL} #"https://api.edamam.com/api/recipes/v2"
    key: ${RECIPES_API_KEY} #"ee6c03e03b5649f47cc9d7eadd5a3183"
    id: ${RECIPES_API_ID} #"f8e22404"

  activities:
    url: "https://fitness-calculator.p.rapidapi.com/activities"
    key: "aa1b080260mshd8f566c12a89594p1ba130jsna4f57523640c"
    host: "fitness-calculator.p.rapidapi.com"

  burnedCalories:
    url: 'https://fitness-calculator.p.rapidapi.com/burnedcalorie'

  macro-calculator:
    url: 'https://fitness-calculator.p.rapidapi.com/macrocalculator'

frontend:
  url: ${FRONTEND_URL} #"http://localhost:4200"

stripe:
  price: ${STRIPE_API_KEY} #"price_1OKhrLKu0TQyqhCeOQx8KRd4"
  api:
    key: ${STRIPE_API_KEY} #"sk_test_51OKQhgKu0TQyqhCeJYJ8H0kYLChtXsf3QgEBEYUdK18PTX2i9kewxffKovuAzFRS2MnfFXSZhCJN33542quMpIod00Jd57EvIT"
    url: ${STRIPE_BILLING_PORTAL_API_URL} #"https://api.stripe.com/v1/billing_portal/sessions"

