spring:
  datasource:
    url: ${DB_URL:empty}
    username: ${DB_USERNAME:empty}
    password: ${DB_PASSWORD:empty}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
        hibernate:
            format_sql: true
    defer-datasource-initialization: false
  flyway:
    enabled: false
    baseline-on-migrate: true
    user: root
    password: root
    baseline-description: "Baseline for FitTrackerApp"
    locations: classpath:db/migration
logging:
  level:
    org.springframework: DEBUG
    app: DEBUG

server:
  port: 8081




api:
  products:
    url: ${PRODUCTS_API_URL:empty}
    key: ${PRODUCTS_API_KEY:empty}
    id: ${PRODUCTS_API_ID:empty}

  recipes:
    url: ${RECIPES_API_URL:empty}
    key: ${RECIPES_API_KEY:empty}
    id: ${RECIPES_API_ID:empty}

  activities:
    url: ${ACTIVITIES_API_URL:empty}
    key: ${ACTIVITIES_API_KEY:empty}
    host: ${ACTIVITIES_API_HOST:empty}

  burnedCalories:
    url: ${BURNED_CALORIES_API_URL:empty}

  macro-calculator:
    url: ${MACRO_CALCULATOR_API_URL:empty}

frontend:
  url: ${FRONTEND_URL:empty}

stripe:
  price: ${STRIPE_API_KEY:empty}
  api:
    key: ${STRIPE_API_KEY:empty}
    url: ${STRIPE_BILLING_PORTAL_API_URL:empty}

